import { z } from "zod";

export const itemSchema = z.object({
  product_id: z.string().optional().nullable(),
  packages: z.coerce.number().optional().nullable(),
  description: z.string().optional().default(""),
  dimensions: z.string().optional().default(""),
  hsn_code: z.string().optional().default(""),
  quantity: z.coerce.number().optional().nullable(),
  unit: z.string().optional().default("PCS"),
  rate: z.coerce.number().optional().nullable(),
  amount: z.coerce.number().optional().nullable(),
  net_weight: z.coerce.number().optional().nullable(),
  gross_weight: z.coerce.number().optional().nullable(),
  origin_country: z.string().optional(),
  image_url: z.string().optional().nullable(),
});

export const containerSchema = z.object({
  container_no: z.string().optional().default(""),
  line_seal_no: z.string().optional().default(""),
  electronic_seal_no: z.string().optional().default(""),
  size: z.string().optional().default("40 FT"),
  quantity: z.string().optional().default("1x40 FT"),
  packages: z.coerce.number().optional().nullable(),
  net_weight: z.coerce.number().optional().nullable(),
  gross_weight: z.coerce.number().optional().nullable(),
  tare_weight: z.coerce.number().optional().nullable(),
  csc_max_weight: z.coerce.number().optional().nullable(),
  vgm_weight: z.coerce.number().optional().nullable(),
  vgm_method: z.string().optional(),
  container_type: z.string().optional(),
});

export const packingLineSchema = z.object({
  serial_no: z.string().optional(),
  description: z.string().optional().default(""),
  pcs: z.coerce.number().optional().nullable(),
  per_pcs_net: z.coerce.number().optional().nullable(),
  per_pcs_gross: z.coerce.number().optional().nullable(),
  net_weight: z.coerce.number().optional().nullable(),
  gross_weight: z.coerce.number().optional().nullable(),
});

export const applicationBodySchema = z.object({
  exporter_name: z.string().optional(),
  exporter_address: z.string().optional(),
  iec_no: z.string().optional(),
  gst_no: z.string().optional(),
  bin_no: z.string().optional(),
  aeo_no: z.string().optional(),
  state_of_origin: z.string().optional(),
  lut_no: z.string().optional(),
  invoice_no: z.string().optional(),
  invoice_date: z.string().optional().nullable(),
  invoice_currency: z.string().optional(),
  exchange_rate: z.coerce.number().optional().nullable(),
  consignee_name: z.string().optional(),
  consignee_address: z.string().optional(),
  consignee_phone: z.string().optional(),
  consignee_email: z.union([z.string().email(), z.literal(""), z.undefined()]).optional(),
  consignee_tax_id: z.string().optional(),
  customer_id: z.string().optional(),
  notify_party: z.string().optional(),
  second_notify: z.string().optional(),
  third_party: z.string().optional(),
  supplier_id: z.string().optional(),
  supplier_name: z.string().optional(),
  supplier_address: z.string().optional(),
  supplier_gst: z.string().optional(),
  factory_address: z.string().optional(),
  port_loading_text: z.string().optional(),
  port_discharge_text: z.string().optional(),
  country_origin: z.string().optional(),
  final_destination_text: z.string().optional(),
  country_id: z.string().optional(),
  payment_terms: z.string().optional(),
  export_terms: z.string().optional(),
  hsn_codes: z.string().optional(),
  products_desc: z.string().optional(),
  lc_no: z.string().optional(),
  lc_issue_date: z.string().optional(),
  lc_expiry_date: z.string().optional(),
  proforma_no: z.string().optional(),
  proforma_date: z.string().optional(),
  latest_shipment_date: z.string().optional(),
  shipping_line: z.string().optional(),
  vessel_name: z.string().optional(),
  voyage_number: z.string().optional(),
  booking_number: z.string().optional(),
  bl_number: z.string().optional(),
  etd: z.string().optional(),
  eta: z.string().optional(),
  bank_name: z.string().optional(),
  bank_account: z.string().optional(),
  bank_swift: z.string().optional(),
  bank_ifsc: z.string().optional(),
  bank_branch: z.string().optional(),
  loading_charge: z.coerce.number().optional(),
  amount_in_words: z.string().optional(),
  declaration: z.string().optional(),
  rodtep_text: z.string().optional(),
  igst_bond_text: z.string().optional(),
  permission_no: z.string().optional(),
  commissionerate: z.string().optional(),
  location_code: z.string().optional(),
  examination_date: z.string().optional(),
  examining_officer: z.string().optional(),
  assigned_to: z.string().optional(),
  version: z.coerce.number().optional(),
  containers: z.array(containerSchema).optional(),
  items: z.array(itemSchema).optional(),
  packing_lines: z.array(packingLineSchema).optional(),
  gst_bills: z.array(z.object({
    bill_no: z.string().optional(),
    bill_date: z.string().optional(),
    company_name: z.string().optional(),
    gst_no: z.string().optional(),
  })).optional(),
  meta: z.record(z.any()).optional(),
  country_requirements: z.record(z.any()).optional(),
  customer_snapshot: z.record(z.any()).optional(),
  supplier_snapshot: z.record(z.any()).optional(),
  bank_snapshot: z.record(z.any()).optional(),
}).passthrough();

export const commentSchema = z.object({
  comment: z.string().min(1, "Comment is required"),
});
